version: 0.0
os: linux
files:
  - source: /
    destination: /opt/tomcat/webapps/
  - source: /TestXMLFile.xml
    destination: /opt/tomcat/webapps/
  - source: /
    destination: /var/www/html/

file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
phases:
  install:
    runtime-versions:
      java: corretto11
    build:
      commands:
      - mvn clean package
artifacts:
  files:
    - target/*.war
    - scripts/server_start.sh
    - scripts/server_stop.sh
    - TestXMLFile.xml
    - appspec.yml
   
   discard-paths: yes  

  AfterInstall:
    - location: server_start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: server_stop.sh
      timeout: 300
      runas: root

